version: '3'
services:
  web:
    image: nginx:1.17.2-alpine
    ports:
      - '8080:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: php:7.3.8-fpm-alpine3.10
    volumes:
      - ./app:/var/www/html
